version: 1.0.{build}
branches:
  only:
  - master
  - development
image: Visual Studio 2022
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build_script:
- cmd: >-
    cd Resources/Deployment/Windows
    
    create_installer.bat
artifacts:
- path: SpaConBridgeSetup*.exe
  name: Installer Binary