version: 1.0.{build}
branches:
  only:
  - master
  - development
image: Ubuntu2004
init:
- sh: >-
    yes | sudo apt-get update

    yes | sudo apt install libasound2-dev libjack-jackd2-dev \
        ladspa-sdk \
        libcurl4-openssl-dev  \
        libfreetype6-dev \
        libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
        libwebkit2gtk-4.0-dev \
        libglu1-mesa-dev mesa-common-dev \
        g++
install:
- sh: >-
    cd "$APPVEYOR_BUILD_FOLDER"

    git submodule update --init --recursive
build_script:
- sh: >-
    cd Resources/Deployment/Linux

    ./build_project.sh
notifications:
- provider: Email
  to:
  - christianahrens@me.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false